Share button that opens a Share Intent for PodcastDetailActivity
SoftwareEngineeringDaily/SEDaily-Android pull request #94
Opened 2018-01-08 01:17 UTC by jaketothepast

Implemented a button that opens a share intent in the Podcast Detail Activity with the text "Check out this episode of Software Engineering Daily: <post link>."

2018-01-08 01:17 UTC, jaketothepast commented
Ready to make any changes you need!

2018-01-08 02:11 UTC, TheHollidayInn commented
Looks great! Do you mind adding a screenshot of the detail activity to the description of this PR?

2018-01-08 02:35 UTC, jaketothepast commented
Of course, here is how the activity renders on my phone complete with a great pic of Stephen Wolfram
![screenshot_20180107-213019](https://user-images.githubusercontent.com/26175457/34657284-a099fa5a-f3f2-11e7-997c-abde09d40a14.png)

2018-01-08 19:59 UTC, TheHollidayInn commented
Thanks! How about adding the share button to the actionbar along with the share icon: https://developer.android.com/training/sharing/shareaction.html

2018-01-09 02:22 UTC, jaketothepast commented
Yep I'll get right on that

2018-01-12 01:19 UTC, jaketothepast commented
Back on it, been a crazy week at work. Sorry in advance for the nooby question, really trying to get my feet wet with Android here, is the actionbar in this context the collapsing toolbar view on the detail activity?

2018-01-16 04:31 UTC, jaketothepast commented
@TheHollidayInn How does this look?

![screenshot_1516077016](https://user-images.githubusercontent.com/26175457/34971936-1a52a23e-fa4c-11e7-93da-4464d72f5077.png)
![screenshot_1516077066](https://user-images.githubusercontent.com/26175457/34971948-33d767f8-fa4c-11e7-886f-f4ec56823bff.png)

2018-01-16 05:19 UTC, TheHollidayInn commented
Ah, I'm sorry. I missed your message. This does look much better! However, the toolbar is the action bar in this context. It looks like you have thing correct, I am going to leave a few more comments.

2018-01-16 05:21 UTC, TheHollidayInn requested changes
Looks good! Almost there :D

2018-01-16 05:21 UTC, TheHollidayInn commented on app/src/main/res/layout/activity_podcast_detail.xml
> +                <Button
What does this button do?

2018-01-16 05:21 UTC, TheHollidayInn commented on app/src/main/res/layout/activity_podcast_detail.xml
> +                android:layout_height="194dp"
Why did you restrict the height of this rather than let it match the parent?

2018-01-16 05:21 UTC, TheHollidayInn commented on app/src/main/res/layout/activity_podcast_detail.xml
> +                    android:contentDescription="Share this Episode"
Can you add these strings to the string resource and use their `@string/`

2018-01-18 03:09 UTC, jaketothepast commented
Ok think at this point @TheHollidayInn we might be done or at least nearly finished. I ended up removing the original share button I added during my first baby steps with Android since now we have the share icon. Also I removed that old button, and changed the layoutWidth back to match parent.

While making those changes I realized I hadn't properly added the share intent to the icon I created, so I added some code for that too.

2018-01-23 00:34 UTC, TheHollidayInn commented
Alright! Looking great :D.

I'm working on a few things this week and will be sure to get this merged in before the next release.

2018-02-05 00:53 UTC, merged